### ISSUE TITLE
Status "Out of Service" for charge points

### ISSUE THREAD

**Issue by Bastoffel** [mKenfenheuer/enbw_chargestations#10]
Hi,

Thanks for this great integration! Would it be possible to reflect the status "Out of Service" for each charge point?
It is possible to receive this information via REST API from EnBW
This would be a nice enhancement!

Thanks!

Cheers,
Bastoffel

**Comment by mKenfenheuer** [comment]
Hi @Bastoffel!

Can you provide more information on this?
I dont have the api responses at hand right now - where is it reflected?

**Comment by Bastoffel** [comment]
Here is an example for the status 'OUT_OF_SERVICE':

`{
    "grouped": false,
    "operator": "EA Energie Architektur GmbH",
    "operatorCode": "DEEAD",
    "priceGroup": "GROUP60",
    "shortAddress": "Airbus-Allee 1 , 28199 Bremen, DE",
    "lat": 53.05432488234004,
    "lon": 8.791628635285539,
    "numberOfChargePoints": 8,
    "availableChargePoints": 3,
    "unknownStateChargePoints": 0,
    "stationId": 417053,
    "viewPort": {
        "lowerLeftLat": 53.054307,
        "lowerLeftLon": 8.791573,
        "upperRightLat": 53.054435999999995,
        "upperRightLon": 8.791791
    },
    "distanceToMyPositionInKm": null,
    "plugTypes": ["CCS", "TYPE_2"],
    "plugTypeNames": ["CCS (Typ 2)", "Typ 2"],
    "favorite": false,
    "maxPowerInKw": 225.0,
    "alwaysOpen": true,
    "handicappedAccessible": null,
    "payment": true,
    "authenticationMethods": ["OTHERS", "REMOTE", "MOBILITY_PLUS_CHARGE_CARD"],
    "hiddenWithActiveProfile": null,
    "stationSummary": "Ladestation Details",
    "additionalInfo": "Airbus - AC 01\nFree publicly accessible\nLeicht zugänglich, sichtbar von der Straße aus\nPI - Airbus Bremen (Gekühlt)\nFree publicly accessible\nLeicht zugänglich, sichtbar von der Straße aus\nPI - Airbus Bremen\nFree publicly accessible\nLeicht zugänglich, sichtbar von der Straße aus\nAirbus - AC 02\nFree publicly accessible\nLeicht zugänglich, sichtbar von der Straße aus",
    "restrictions": null,
    "openingHours": null,
    "openingTimes": {
        "regularHours": [],
        "twentyFourSeven": true,
        "closedOnHolidays": null,
        "nextOpeningTime": null,
        "nextClosingTime": null
    },
    "chargePoints": [{
        "evseId": "DE*EAD*E50003",
        "status": "OUT_OF_SERVICE",
        "state": {
            "updatedAt": 1723569400797,
            "value": "OUT_OF_SERVICE"
        },
        "connectors": [{
            "chargePlugTypeGroup": "CCS",
            "plugTypeName": "CCS (Typ 2)",
            "maxPowerInKw": 225.0,
            "cableAttached": true,
            "tariffInfo": {
                "tariffGroup": "DC_CHARGER",
                "tariffDescription": "Preis je DC kWh: Ab 0,89 € \nmit Blockiergebühr*",
                "paymentText": "Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt."
            }
        }],
        "stationNumber": null,
        "chargePointNumber": null,
        "chargePointLabel": null,
        "handicappedAccessible": null
    }, {
        "evseId": "DE*EAD*E50004",
        "status": "OUT_OF_SERVICE",
        "state": {
            "updatedAt": 1723569400824,
            "value": "OUT_OF_SERVICE"
        },
        "connectors": [{
            "chargePlugTypeGroup": "CCS",
            "plugTypeName": "CCS (Typ 2)",
            "maxPowerInKw": 225.0,
            "cableAttached": true,
            "tariffInfo": {
                "tariffGroup": "DC_CHARGER",
                "tariffDescription": "Preis je DC kWh: Ab 0,89 € \nmit Blockiergebühr*",
                "paymentText": "Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt."
            }
        }],
        "stationNumber": null,
        "chargePointNumber": null,
        "chargePointLabel": null,
        "handicappedAccessible": null
    }, {
        "evseId": "DE*EAD*E50005",
        "status": "AVAILABLE",
        "state": {
            "updatedAt": 1724157059474,
            "value": "AVAILABLE"
        },
        "connectors": [{
            "chargePlugTypeGroup": "CCS",
            "plugTypeName": "CCS (Typ 2)",
            "maxPowerInKw": 120.0,
            "cableAttached": true,
            "tariffInfo": {
                "tariffGroup": "DC_CHARGER",
                "tariffDescription": "Preis je DC kWh: Ab 0,89 € \nmit Blockiergebühr*",
                "paymentText": "Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt."
            }
        }],
        "stationNumber": null,
        "chargePointNumber": null,
        "chargePointLabel": null,
        "handicappedAccessible": null
    }, {
        "evseId": "DE*EAD*E50006",
        "status": "AVAILABLE",
        "state": {
            "updatedAt": 1724160199407,
            "value": "AVAILABLE"
        },
        "connectors": [{
            "chargePlugTypeGroup": "CCS",
            "plugTypeName": "CCS (Typ 2)",
            "maxPowerInKw": 120.0,
            "cableAttached": true,
            "tariffInfo": {
                "tariffGroup": "DC_CHARGER",
                "tariffDescription": "Preis je DC kWh: Ab 0,89 € \nmit Blockiergebühr*",
                "paymentText": "Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt."
            }
        }],
        "stationNumber": null,
        "chargePointNumber": null,
        "chargePointLabel": null,
        "handicappedAccessible": null
    }, {
        "evseId": "DE*EAD*E100131",
        "status": "OCCUPIED",
        "state": {
            "updatedAt": 1724152224617,
            "value": "OCCUPIED"
        },
        "connectors": [{
            "chargePlugTypeGroup": "TYPE_2",
            "plugTypeName": "Typ 2",
            "maxPowerInKw": 22.0,
            "cableAttached": false,
            "tariffInfo": {
                "tariffGroup": "AC_CHARGER",
                "tariffDescription": "Preis je AC kWh: Ab 0,89 € \nmit Blockiergebühr*",
                "paymentText": "Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt."
            }
        }],
        "stationNumber": null,
        "chargePointNumber": null,
        "chargePointLabel": null,
        "handicappedAccessible": null
    }, {
        "evseId": "DE*EAD*E100132",
        "status": "AVAILABLE",
        "state": {
            "updatedAt": 1724150070265,
            "value": "AVAILABLE"
        },
        "connectors": [{
            "chargePlugTypeGroup": "TYPE_2",
            "plugTypeName": "Typ 2",
            "maxPowerInKw": 22.0,
            "cableAttached": false,
            "tariffInfo": {
                "tariffGroup": "AC_CHARGER",
                "tariffDescription": "Preis je AC kWh: Ab 0,89 € \nmit Blockiergebühr*",
                "paymentText": "Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt."
            }
        }],
        "stationNumber": null,
        "chargePointNumber": null,
        "chargePointLabel": null,
        "handicappedAccessible": null
    }, {
        "evseId": "DE*EAD*EE100129",
        "status": "OCCUPIED",
        "state": {
            "updatedAt": 1724159634304,
            "value": "OCCUPIED"
        },
        "connectors": [{
            "chargePlugTypeGroup": "TYPE_2",
            "plugTypeName": "Typ 2",
            "maxPowerInKw": 22.0,
            "cableAttached": false,
            "tariffInfo": {
                "tariffGroup": "AC_CHARGER",
                "tariffDescription": "Preis je AC kWh: Ab 0,89 € \nmit Blockiergebühr*",
                "paymentText": "Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt."
            }
        }],
        "stationNumber": null,
        "chargePointNumber": null,
        "chargePointLabel": null,
        "handicappedAccessible": null
    }, {
        "evseId": "DE*EAD*EE100130",
        "status": "OCCUPIED",
        "state": {
            "updatedAt": 1724134274996,
            "value": "OCCUPIED"
        },
        "connectors": [{
            "chargePlugTypeGroup": "TYPE_2",
            "plugTypeName": "Typ 2",
            "maxPowerInKw": 22.0,
            "cableAttached": false,
            "tariffInfo": {
                "tariffGroup": "AC_CHARGER",
                "tariffDescription": "Preis je AC kWh: Ab 0,89 € \nmit Blockiergebühr*",
                "paymentText": "Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt."
            }
        }],
        "stationNumber": null,
        "chargePointNumber": null,
        "chargePointLabel": null,
        "handicappedAccessible": null
    }],
    "tariffInformations": ["Es gilt ausschließlich der oben angezeigte Preis ungeachtet hiervon möglicherweise abweichender Angaben des Betreibers, insbesondere in dessen unten ersichtlichen Betreiber-Informationen oder an der Ladesäule. Alle Preise inkl. gesetzlicher MwSt.", "*Bitte unsere Blockiergebühr beachten\nDC: Ab 240 Minuten 0,10 € pro Minute\nAC: Ab 240 Minuten 0,10 € pro Minute\nMaximal: bis 12,00 €"],
    "supportInfo": {
        "supportHotLine": "+4935165683939"
    },
    "parkingFeeDescriptions": "*Bitte unsere Blockiergebühr beachten\nDC: Ab 240 Minuten 0,10 € pro Minute\nAC: Ab 240 Minuten 0,10 € pro Minute\nMaximal: bis 12,00 €",
    "pricingInfo": {
        "priceType": "GLOBAL_MIN",
        "chargePerKwhInCent": 39,
        "freeParkingInMinutes": 240,
        "blockingFeePerMinuteInCent": 10,
        "maxBlockingFeePerChargingInCent": 1200
    }
}`

**Comment by mKenfenheuer** [comment]
Hi @Bastoffel!

Can you check with the latest release? It will report as "on" and the attribute "isOutOfService" is set to true if the station is out of service.

![grafik](https://github.com/user-attachments/assets/cf9daf4b-3c1f-4e7b-ba29-864c9f5a63c3)

**Comment by Bastoffel** [comment]
Perfect, thank you very much for the quick implementation! That's really useful.
